---
title: 編譯器錯誤 CS0724
ms.date: 07/20/2015
f1_keywords:
- CS0724
helpviewer_keywords:
- CS0724
ms.assetid: bcdb2017-7a43-4242-b4e2-a1ae03d6d73f
ms.openlocfilehash: feae6b666067e652e1021b1f173bab56c7a27dc0
ms.sourcegitcommit: ad800f019ac976cb669e635fb0ea49db740e6890
ms.translationtype: MT
ms.contentlocale: zh-TW
ms.lasthandoff: 10/29/2019
ms.locfileid: "73039381"
---
# <a name="compiler-error-cs0724"></a><span data-ttu-id="bb04d-102">編譯器錯誤 CS0724</span><span class="sxs-lookup"><span data-stu-id="bb04d-102">Compiler Error CS0724</span></span>

<span data-ttu-id="bb04d-103">最內層 catch 子句中巢狀 finally 子句不允許沒有引數的 throw 陳述式</span><span class="sxs-lookup"><span data-stu-id="bb04d-103">A throw statement with no arguments is not allowed in a finally clause that is nested inside the nearest enclosing catch clause</span></span>

## <a name="example"></a><span data-ttu-id="bb04d-104">範例</span><span class="sxs-lookup"><span data-stu-id="bb04d-104">Example</span></span>

<span data-ttu-id="bb04d-105">下列範例會產生 CS0724，因為 `finally` 子句區塊內的 `throw` 語句：</span><span class="sxs-lookup"><span data-stu-id="bb04d-105">The following example generates CS0724 because of the `throw` statement inside the `finally` clause block:</span></span>

```csharp  
// CS0724.cs  
using System;  
  
class Program
{
    static void Test()
    {
        try
        {
            throw new Exception();
        }
        catch
        {
            try
            {
            }
            finally
            {
                throw; // CS0724
            }
        }
    }

    static void Main()
    {
    }
}
```
