---
title: "'Catch' 不可以出現在 'Try' 陳述式之外。"
ms.date: 07/20/2015
f1_keywords:
- bc30380
- vbc30380
helpviewer_keywords:
- BC30380
ms.assetid: 73ce950d-881f-4532-8024-40a4930abd32
ms.openlocfilehash: f9ce965d1d983743796f8cc66ae20ffb018a07bc
ms.sourcegitcommit: 0be8a279af6d8a43e03141e349d3efd5d35f8767
ms.translationtype: HT
ms.contentlocale: zh-TW
ms.lasthandoff: 04/18/2019
ms.locfileid: "59295909"
---
# <a name="catch-cannot-appear-outside-a-try-statement"></a>'Catch' 不可以出現在 'Try' 陳述式之外。
`Catch` 必須出現在 `Try...Catch...Finally` 陳述式區塊內。 `Catch` 區塊中有不必要的 `Try` 陳述式，或 `Catch` 陳述式出現在其對應 `Try` 區塊的範圍之外。  
  
 **錯誤 ID:** BC30380  
  
## <a name="to-correct-this-error"></a>更正這個錯誤  
  
1. 如果 `Catch` 陳述式不是必要的，請刪除它，或放在 `Try...Catch...Finally` 陳述式區塊中。  
  
## <a name="see-also"></a>另請參閱

- [Try...Catch...Finally 陳述式](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
